Parameters:
  AutoScaleGroupName:
    Type: String

Resources:
  ScaleInPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: { Ref: AutoScaleGroupName }
      Cooldown: '120'
      ScalingAdjustment: '1'
  
  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '30'
      Period: '60'
      AlarmActions:
      - Ref: ScaleInPolicy
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value: {Ref: AutoScaleGroupName}
      ComparisonOperator: LessThanThreshold
      MetricName: CPUUtilization
