Parameters:
  LaunchConfigName:
    Type: String
    Description: Launch configurtion name
Resources:
  SimpleLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      LaunchConfigurationName: {Ref: LaunchConfigName}
      ImageId: 'ami-0de53d8956e8dcf80'
      InstanceType: t2.micro
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs: 
            VolumeSize: "50"
            VolumeType: "io1"
            Iops: 200
      UserData:
          Fn::Base64:
            Fn::Join:
              - ''
              - - "#!/bin/bash -xe\n"
                - 'exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1\n'
                - '# Install the files and packages \n'
                - 'yum -y update '
                - 'sudo amazon-linux-extras install epel '
                - 'yum -y install stress '
                - 'stress --cpu 1 --timeout 360 '